name: Specific Video file
on: [push]

jobs:
  small-model:
    name: run small model
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: download small model
      run: |
        mkdir -p models
        curl -LJ https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin \
          --output models/ggml-small.bin

    - name: speech to text
      uses: ./
      with:
        model: ./models/ggml-small.bin
        audio_path: ./testdata/jfk.wav
        debug: true

    - name: show txt data
      run: |
        echo "show txt file"
        cat ./testdata/jfk.txt

  medium-model:
    name: run medium model
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: download medium model
      run: |
        mkdir -p models
        curl -LJ https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin \
          --output models/ggml-medium.bin

    - name: speech to text
      uses: ./
      with:
        model: ./models/ggml-medium.bin
        audio_path: ./testdata/jfk.wav
        debug: true

    - name: show txt data
      run: |
        echo "show txt file"
        cat ./testdata/jfk.txt
